### ISSUE TITLE
Feature request: Pushover

### ISSUE THREAD

**Issue by nightah** [Ardakilic/alerthub#14]
I would love to see alerthub with support for [Pushover](https://pushover.net/), as another alternative to lets say Pushbullet.

**Comment by Ardakilic** [comment]
Hello, please check the master branch. I've just implemented a pushover feature, however, since I don't have a pushover account, I can't test myself.

Here's my commit regarding the Pushover: https://github.com/Ardakilic/alerthub/commit/90bb4c58d7cfcd6e810c049696c4fbb16b594156

**Comment by nightah** [comment]
I've just noticed that the primary container I use for this has been archived, so I'm just quickly putting together an updated container for AlertHub and will test shortly.

**Comment by nightah** [comment]
Confirmed the Pushover hook works as expected.

Also I've setup: https://github.com/antilax-3/docker-alerthub if you want to reference that somewhere in your repo.
Please let me know if you do because I can PM you a webhook URL so your commits will result in a Jenkins build for Alerthub.

**Comment by Ardakilic** [comment]
Just released v1.3.0 with your Docker container and the Pushover change 🎉 

https://github.com/Ardakilic/alerthub/releases/tag/v1.3.0

Thanks for the test of Pushover integration 🙏
