### ISSUE TITLE
Version incorrect?

### ISSUE THREAD

**Issue by Jekotia** [Ardakilic/alerthub#3]
When cloning this repo and building from source, it reports version 1.1.0 instead of 1.2.0 when run.

> alerthub@1.1.0 start /home/nodejs/alerthub

**Comment by Ardakilic** [comment]
Hey there, 

Thanks for the report! It seems I've forgot to update `package.json` while merging. I'll fix this in the next release. Please ignore that number for the time being, your app is indeed 1.2.0.

**Comment by Ardakilic** [comment]
Closing this due to updated version 1.2.1.
