### ISSUE TITLE
Feature request: hooks

### ISSUE THREAD

**Issue by Jekotia** [Ardakilic/alerthub#4]
It would be nice if, when alerthub detects a new release, it would run a specified hook.

For example, when an update to alerthub is detected, it runs a shell script containing the webhook to trigger a build on dockerhub, rebuilding jekotia/alerthub with the latest version of alerthub

**Comment by Jekotia** [comment]
I think running the script would be best.

I initially was thinking of webhooks, and then my mind wandered to git commit hooks as I wrote the request and realised it would be better to go the script route. I feel that it provides the greatest flexibility, since you can still easily do a webhook, but can also do more if you so wish.

**Comment by Ardakilic** [comment]
I believe this may be obsolete with #37
